### ISSUE TITLE
Update to version 1.20.2

### ISSUE THREAD

**Issue by saknl** [flathub/de.bund.ausweisapp.ausweisapp2#1]
Hi,
could you update to version 1.20.2 released on September 2nd?

**Comment by e-user** [comment]
Hi @saknl, please let me know whether the version obtained through `flatpak install https://dl.flathub.org/build-repo/30098/de.bund.ausweisapp.ausweisapp2.flatpakref` works for you.

**Comment by saknl** [comment]
Thank you @e-user for your work. The link you gave me doesn't work but I could get the version from flathub-beta and it works without any problems!

**Comment by e-user** [comment]
@saknl nice. I will merge the beta version back to stable. Thanks for your help with testing!

**Comment by e-user** [comment]
1.20.2 is now available in stable.
