### ISSUE TITLE
Android smartphone could not be paired with laptop

### ISSUE THREAD

**Issue by sergeantbl** [flathub/de.bund.ausweisapp.ausweisapp2#18]
Hello everyone,

I just tried to do the online authentication to register for unemployment via Bundesagentur für Arbeit. 

The desktop version couldn't find my smartphone and therefore I couldn't pair. Thus, I used the Windows application on a Windows laptop and I could successfully do the authentication. All three devices are in the same Wifi.

**Device specs:**

**Linux laptop:**
- Dell XPS 13 on Linux Mint 21
- Virus system: none but firewall is activated

**Windows laptop**
- Lenovo YOGA 530-14IKB
- Virus system: Bitdefender and Microsoft Defender Firewall

**Smartphone:**
Samsung S21 FE on Android 13

I suppose that the actual issue is the firewall settings. Let me know how this could be fixed respectively what I can provide you to support you in solving this issue.

Best,

**Comment by christian179717** [comment]
Same problem, even with all Linux clients
First I used the F-Droid App for Android, but even with the PlayStore App it doesn't work
Fix would be great

System details:
Linux Mint 21 Cinnamon (Dell Latitude E5550)

Android Version 9 (Huawei P10)
App Version 1.26.3

**Comment by ausweisapp2comment** [comment]
Had the same issue but I think I have a (the?) solution.

Pairing works with the Windows App and my smartphone but not with Linux Mint Cinnamon 21.2.

Apparently, the firewall causes this. Disabling it will show my device in the menu. From the Windows App I know that it uses the port 24727. So introducing an exception to the firewall's rule set for this port solved the issue.

Maybe this can be implemented such that it works automatically (or at least it should mention the port in the manual.

**Comment by christian179717** [comment]
@ausweisapp2comment I tried your way but sadly it doesn't worked. First I only create a rule for port 24727 after this did not work I disabled the firewall (ufw) I tried again, even this did not work.
Did you do something else, e.g. run the Ausweisapp as administrator?

**Comment by ausweisapp2comment** [comment]
@christian179717 Too bad. I really thought this would be it.
Sadly, that's all I did. Just introduced a rule for the port. Okay, and disabling my VPN as it is mentioned in the manual. I started the flatpack just normally from the menu. Actually I did not need to restart it after introducing the firewall exception. It immediately showed the device.

**Comment by mbratz** [comment]
I can confirm that the flatpak version de.bund.ausweisapp.ausweisapp2:2.0.0 on Linux Mint 21.2 Cinammon works with a Samsung Galaxy 21 Ultra and the AusweisApp 2.0.0 from 03.11.2023. I was able to link the devices in the same Wifi-network and to login to DRV.
It was not necessary to open any ports or deactivate a firewall.

**Comment by christian179717** [comment]
With another device it works for me too. I don't know why, but with the device it didn't work, I have some other problems with network communication too.

**Comment by boustanihani** [comment]
Disabling the firewall or openning `TCP` & `UDP` port `24727` worked for me.

**Comment by provokateurin** [comment]
Please don't disable your firewall! Only allow the necessary ports!

**Comment by itsjakobx** [comment]
As for me it was docker blocking ausweisapp.. I cannot explain why:

```
systemctl stop docker
nft flush ruleset
```
