### ISSUE TITLE
SCL011 reader stopped working in 2.2.1

### ISSUE THREAD

**Issue by fungs** [flathub/de.bund.ausweisapp.ausweisapp2#56]
Upgrading from 2.2.0 to 2.2.1, it stopped detecting my reader SCM Microsystems SCL011.

This may be an upstream bug, but https://github.com/Governikus/AusweisApp/ does not have an issue tracker and there is no official Linux non-flatpak build to validate against.

It may also be related to the upgrade of pcsc-lite from 2.1.0 to 2.3.0: https://github.com/flathub/de.bund.ausweisapp.ausweisapp2/commit/9a1a37c73cc52678d2afcf2fcfdce1bd6f7f83c0

Note: The reader was officially distributed as a starter pack when the electronic ID was introduced. But in version 2.2.0 there appears a notice that it is not officially supported (wtf) and that it might not work properly. However, it works like a charm until 2.2.0

**Comment by fungs** [comment]
@misery that's probably it.

I assume that, by upgrading the system PCSC server version, the issue can be fixed then: https://ludovicrousseau.blogspot.com/2022/02/accessing-smart-cards-from-inside.html

While the Flatpak version cannot fix the issue itself, it could just stick to the older version of the pscs-lite and upgrade later. Given that the new version 2.3.0 was released about two months ago, we can expect that it is not contained in any major stable Linux distribution, yet. So many users will run into that issue.

Seems like https://github.com/flathub/de.bund.ausweisapp.ausweisapp2/issues/53 is the reverse case.

According to the authors, PCSC is not made for use in Flatpak (otherwise I would consider this behavior a clear bug).

Anyway, one solution is to downgrade the flatpak and mask it to prevent updates.

**Comment by Erick555** [comment]
Something that flatpak can do is having one pcsc version in main flathub and other in flathub-beta repo then instruct users which version the should install. See [example](https://github.com/flathub/com.yubico.yubioath/blob/f0726352ec9bf9a2caed77556741cdc4abdce49a/README.md)
